### ISSUE TITLE
Chore: Setup Dockerization

### ISSUE THREAD

**Issue by felipos** [murilovidal/apod-telegram-bot#8]
We need some dockerization to be able to deploy the application easily, for local development or production use.

### Questions that needs to be answered: 

1. What is Docker and what problem does it solves?
2. How is a container different from a virtual machine?
3. Why, in your opinion, docker became so popular?

**Comment by murilovidal** [comment]
1. Docker enables the deploy of containerized applications packed with its own dependencies and environment. This solves possible problems of dependecy conflict, scalability and eases the standardization of development and production environments.
2. A virtual machine is an entire operating system that is run as guest of another OS. A container is a layer that contains one or several applications and its required libraries The container does not virtualize an entire OS, it runs with isolated processes between other containers that are being run on the same operating system.
3. Docker is popular, in my opinion, because it is a form of environment virtualization that is lightweight and scalable. It can be used to deploy and manage apps and to share development or testing environments.
